export const SUPPORTED_CUISINES = [
  { label: "African", value: "african" },
  { label: "Asian", value: "asian" },
  { label: "American", value: "american" },
  { label: "British", value: "british" },
  { label: "Cajun", value: "cajun" },
  { label: "Caribbean", value: "caribbean" },
  { label: "Chinese", value: "chinese" },
  { label: "Eastern European", value: "eastern-european" },
  { label: "European", value: "european" },
  { label: "French", value: "french" },
  { label: "German", value: "german" },
  { label: "Greek", value: "greek" },
  { label: "Indian", value: "indian" },
  { label: "Irish", value: "irish" },
  { label: "Italian", value: "italian" },
  { label: "Japanese", value: "japanese" },
  { label: "Jewish", value: "jewish" },
  { label: "Korean", value: "korean" },
  { label: "Latin American", value: "latin-american" },
  { label: "Mediterranean", value: "mediterranean" },
  { label: "Mexican", value: "mexican" },
  { label: "Middle Eastern", value: "middle-eastern" },
  { label: "Nordic", value: "nordic" },
  { label: "Southern", value: "southern" },
  { label: "Spanish", value: "spanish" },
  { label: "Thai", value: "thai" },
  { label: "Vietnamese", value: "vietnamese" },
];
